export OMP_NUM_THREADS=2
pyt -m torch.distributed.launch --nproc_per_node=4 run.py configs/seq/seq103.yaml predict_features_cls --dist --dist-val --num-workers 2 --kfold 0 --save-probas-dir ../data/train-pe-cls-probas/fold0 --checkpoint ../checkpoints/seq103/fold0/TRANSFORMERCLS_007_VM-0.1625.PTH
pyt -m torch.distributed.launch --nproc_per_node=4 run.py configs/seq/seq103.yaml predict_features_cls --dist --dist-val --num-workers 2 --kfold 1 --save-probas-dir ../data/train-pe-cls-probas/fold1 --checkpoint ../checkpoints/seq103/fold1/TRANSFORMERCLS_009_VM-0.1530.PTH
pyt -m torch.distributed.launch --nproc_per_node=4 run.py configs/seq/seq103.yaml predict_features_cls --dist --dist-val --num-workers 2 --kfold 2 --save-probas-dir ../data/train-pe-cls-probas/fold2 --checkpoint ../checkpoints/seq103/fold2/TRANSFORMERCLS_007_VM-0.1625.PTH
pyt -m torch.distributed.launch --nproc_per_node=4 run.py configs/seq/seq103.yaml predict_features_cls --dist --dist-val --num-workers 2 --kfold 3 --save-probas-dir ../data/train-pe-cls-probas/fold3 --checkpoint ../checkpoints/seq103/fold3/TRANSFORMERCLS_007_VM-0.1586.PTH
pyt -m torch.distributed.launch --nproc_per_node=4 run.py configs/seq/seq103.yaml predict_features_cls --dist --dist-val --num-workers 2 --kfold 4 --save-probas-dir ../data/train-pe-cls-probas/fold4 --checkpoint ../checkpoints/seq103/fold4/TRANSFORMERCLS_009_VM-0.1536.PTH

pyt -m torch.distributed.launch --nproc_per_node=4 run.py configs/seq/seq103b.yaml predict_features_cls --dist --dist-val --num-workers 2 --kfold 0 --save-probas-dir ../data/train-pe-cls-probas-b/fold0 --checkpoint ../checkpoints/seq103b/fold0/TRANSFORMERCLS_008_VM-0.1620.PTH
pyt -m torch.distributed.launch --nproc_per_node=4 run.py configs/seq/seq103b.yaml predict_features_cls --dist --dist-val --num-workers 2 --kfold 1 --save-probas-dir ../data/train-pe-cls-probas-b/fold1 --checkpoint ../checkpoints/seq103b/fold1/TRANSFORMERCLS_009_VM-0.1522.PTH
pyt -m torch.distributed.launch --nproc_per_node=4 run.py configs/seq/seq103b.yaml predict_features_cls --dist --dist-val --num-workers 2 --kfold 2 --save-probas-dir ../data/train-pe-cls-probas-b/fold2 --checkpoint ../checkpoints/seq103b/fold2/TRANSFORMERCLS_009_VM-0.1619.PTH
pyt -m torch.distributed.launch --nproc_per_node=4 run.py configs/seq/seq103b.yaml predict_features_cls --dist --dist-val --num-workers 2 --kfold 3 --save-probas-dir ../data/train-pe-cls-probas-b/fold3 --checkpoint ../checkpoints/seq103b/fold3/TRANSFORMERCLS_008_VM-0.1582.PTH
pyt -m torch.distributed.launch --nproc_per_node=4 run.py configs/seq/seq103b.yaml predict_features_cls --dist --dist-val --num-workers 2 --kfold 4 --save-probas-dir ../data/train-pe-cls-probas-b/fold4 --checkpoint ../checkpoints/seq103b/fold4/TRANSFORMERCLS_009_VM-0.1547.PTH

pyt -m torch.distributed.launch --nproc_per_node=4 run.py configs/seq/seq103c.yaml predict_features_cls --dist --dist-val --num-workers 2 --kfold 0 --save-probas-dir ../data/train-pe-cls-probas-c/fold0 --checkpoint ../checkpoints/seq103c/fold0/TRANSFORMERCLS_009_VM-0.1620.PTH
pyt -m torch.distributed.launch --nproc_per_node=4 run.py configs/seq/seq103c.yaml predict_features_cls --dist --dist-val --num-workers 2 --kfold 1 --save-probas-dir ../data/train-pe-cls-probas-c/fold1 --checkpoint ../checkpoints/seq103c/fold1/TRANSFORMERCLS_009_VM-0.1537.PTH
pyt -m torch.distributed.launch --nproc_per_node=4 run.py configs/seq/seq103c.yaml predict_features_cls --dist --dist-val --num-workers 2 --kfold 2 --save-probas-dir ../data/train-pe-cls-probas-c/fold2 --checkpoint ../checkpoints/seq103c/fold2/TRANSFORMERCLS_009_VM-0.1624.PTH
pyt -m torch.distributed.launch --nproc_per_node=4 run.py configs/seq/seq103c.yaml predict_features_cls --dist --dist-val --num-workers 2 --kfold 3 --save-probas-dir ../data/train-pe-cls-probas-c/fold3 --checkpoint ../checkpoints/seq103c/fold3/TRANSFORMERCLS_008_VM-0.1576.PTH
pyt -m torch.distributed.launch --nproc_per_node=4 run.py configs/seq/seq103c.yaml predict_features_cls --dist --dist-val --num-workers 2 --kfold 4 --save-probas-dir ../data/train-pe-cls-probas-c/fold4 --checkpoint ../checkpoints/seq103c/fold4/TRANSFORMERCLS_009_VM-0.1562.PTH